### ISSUE TITLE
Live energy monitoring only when the Tuya mobile app is open?

### ISSUE THREAD

**Issue by schteff** [rospogrigio/localtuya#380] opened 2021-03-04 15:30 UTC
Hi!

I have a couple [SH-P02E](https://www.deltaco.se/produkter/deltaco/smart-home/grenuttag/SH-P02E) sockets with energy monitoring. 

My problem is that I only seem to get live energy monitoring in Home Assistant when I use the Tuya Smart app to see the energy consumption. If i don't have the app running on this screen the consumption flatlines in Home Assistant. 

Is this the expected behaviour? Is it a problem that I have the Tuya app installed?

![image](https://user-images.githubusercontent.com/2564884/109987165-ad8e6c00-7d06-11eb-8915-1e0b549a2e62.png)

Using version 3.2.1 of localtuya

**Comment by postlund** [comment] 2021-03-04 15:57
Duplicate of #87.

**Closed by postlund** 2021-03-04 15:57 UTC
