### ISSUE TITLE
LocalTuya integration going unavailable at least once a day

### ISSUE THREAD

**Issue by escobarin3** [rospogrigio/localtuya#1258] opened 2023-01-23 01:19 UTC
Hi, 
A couple of days ago my LocalTuya integration started to go unavailable at least once a day. I don't understand the reason and I'm not very good understanding the error messages nor the logs. 
Can you help me find out the reason of this error? Reloading the integration won't solve the issue, the only solution is to restart HA. 

![Captura de Pantalla 2023-01-22 a la(s) 8 10 03 p  m](https://user-images.githubusercontent.com/85810778/213951624-dbdb327b-f69a-4120-83b7-d6250436d22c.png)

Logger: homeassistant.components.websocket_api.http.connection
Source: config_entries.py:1111
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:10:01 PM (1 occurrences)
Last logged: 8:10:01 PM

[140330748998896] The config entry localtuya (localtuya) with entry_id c0423c56a1535434046c08917f78ee30 cannot be unloaded because it is not in a recoverable state (ConfigEntryState.FAILED_UNLOAD)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 751, in admin_handler
    await result
  File "/config/custom_components/localtuya/__init__.py", line 84, in _handle_reload
    await asyncio.gather(*reload_tasks)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1128, in async_reload
    unload_result = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1111, in async_unload
    raise OperationNotAllowed(
homeassistant.config_entries.OperationNotAllowed: The config entry localtuya (localtuya) with entry_id c0423c56a1535434046c08917f78ee30 cannot be unloaded because it is not in a recoverable state (ConfigEntryState.FAILED_UNLOAD)

**Comment by escobarin3** [comment] 2023-01-23 03:41
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/common.py:273
Integration: LocalTuya (documentation, issues)
First occurred: 10:28:32 PM (1 occurrences)
Last logged: 10:28:32 PM

Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 311, in async_unload_entry
    await device.close()
  File "/config/custom_components/localtuya/common.py", line 308, in close
    await self._connect_task
  File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
    and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by CloCkWeRX** [comment] 2023-01-23 10:47
@escobarin3 I managed to trigger this as well.

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/common.py:273
Integration: LocalTuya (documentation, issues)
First occurred: 9:10:21 PM (1 occurrences)
Last logged: 9:10:21 PM

Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 312, in async_unload_entry
    await device.close()
  File "/config/custom_components/localtuya/common.py", line 308, in close
    await self._connect_task
  File "/config/custom_components/localtuya/common.py", line 273, in _make_connection
    and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'
```

I suspect there is a device with a non integer scan interval set.

**Comment by CloCkWeRX** [comment] 2023-01-23 10:55
Reproduce steps:

* Edit an entity.
* The scan interval gets set to ''
* Save

Expected:
It gets ignored/cast to int.

Actual:
Exceptions as per above.

**Comment by CloCkWeRX** [comment] 2023-01-23 11:18
Duplicate of https://github.com/rospogrigio/localtuya/issues/1248

**Comment by escobarin3** [comment] 2023-01-24 01:08
Hello again... .
Just tried downgrading to v 4.1.0... and same issue... 


This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/localtuya/common.py:267
Integration: LocalTuya (documentation, issues)
First occurred: 8:05:03 PM (1 occurrences)
Last logged: 8:05:03 PM

Error unloading entry localtuya for localtuya
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 533, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/localtuya/__init__.py", line 311, in async_unload_entry
    await device.close()
  File "/config/custom_components/localtuya/common.py", line 302, in close
    await self._connect_task
  File "/config/custom_components/localtuya/common.py", line 267, in _make_connection
    and self._dev_config_entry[CONF_SCAN_INTERVAL] > 0
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by dreamtheater39** [comment] 2023-01-30 05:35
I have the same issue.....a reload config entries service call doesn't receive it either. I need to manually go and reload the integration and it instantly rectifies itself.

**Comment by escobarin3** [comment] 2023-01-31 01:57
> I have the same issue.....a reload config entries service call doesn't resolve it either. I need to manually go and reload the integration and it instantly rectifies itself.

At least you can reload the integration... I have to restart HA in order to get things back to work for a while. 

My Local Tuya integration has not been working for a while now... at least for the las 2 weeks. My devices become unavailable every now and then... it is becoming very unrealiable. This is a new thing obviosly because it worked fine for years....  :(

I cannot find anyting in my logs that indicates any possible issue... 
I cannot edit a device or reload the integration bacause all my devices go offline/unavailable... forcing me to restart HA... 
Any ideas?

My most recent log shows this: 

Logger: homeassistant.components.websocket_api.http.connection
Source: config_entries.py:1111
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 8:50:46 PM (1 occurrences)
Last logged: 8:50:46 PM

[139952805691888] The config entry localtuya (localtuya) with entry_id c0423c56a1535434046c08917f78ee30 cannot be unloaded because it is not in a recoverable state (ConfigEntryState.FAILED_UNLOAD)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 751, in admin_handler
    await result
  File "/config/custom_components/localtuya/__init__.py", line 84, in _handle_reload
    await asyncio.gather(*reload_tasks)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1128, in async_reload
    unload_result = await self.async_unload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1111, in async_unload
    raise OperationNotAllowed(
homeassistant.config_entries.OperationNotAllowed: The config entry localtuya (localtuya) with entry_id c0423c56a1535434046c08917f78ee30 cannot be unloaded because it is not in a recoverable state (ConfigEntryState.FAILED_UNLOAD)

**Comment by escobarin3** [comment] 2023-02-07 22:16
This solved my issue. Everything has been working perfect now. 

https://github.com/rospogrigio/localtuya/issues/1253#issuecomment-1412069911

**Closed** 2023-02-24 13:09 UTC
