### ISSUE TITLE
After update to HA  2022.06 I get the following "WARNING MESSAGE"

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [rospogrigio/localtuya#845] opened 2022-06-01 17:50 UTC
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:103
First occurred: 20:46:51 (1 occurrences)
Last logged: 20:46:51

Detected integration that uses deprecated `async_get_registry` to access entity registry, use async_get instead. Please report issue to the custom component author for localtuya using this method at custom_components/localtuya/__init__.py, line 315: ent_reg = await er.async_get_registry(hass)

**Comment by tankdeer** [comment] 2022-06-02 00:49
Just came here to post the same issue.

**Comment by golds69** [comment] 2022-06-02 10:05
I have the same warning message

**Comment by rcblackwell** [comment] 2022-06-02 21:13
I’m receiving the same error.

**Comment by pergolafabio** [comment] 2022-06-02 21:17
Pls stop posting "I have the same"...

**Comment by garry0garry** [comment] 2022-06-03 06:17
https://github.com/home-assistant/core/issues/72951

**Comment by talondnb** [comment] 2022-06-03 06:46
The same warning, I have.

**Comment by homecb** [comment] 2022-06-03 23:45
@garry0garry Please remove that link. It's irrelevant. As pointed out, you reported it in the wrong repo.

**Comment by Jaguaza** [comment] 2022-06-04 06:52
The same warning, I have.

**Comment by zyigo** [comment] 2022-06-04 09:32
The have, warning, same I.

**Comment by JonasPed** [comment] 2022-06-05 19:39
This is a duplicate of #830

**Comment by jeremysherriff** [comment] 2022-06-05 22:57
Fixed in PR #842 please follow that for updates.

**Closed** 2022-06-06 13:53 UTC
Labels: bug
