### ISSUE TITLE
Connection to device succeeded but no datapoints found

### ISSUE THREAD

**Issue by SvetZitrka** [rospogrigio/localtuya#271] opened 2020-12-28 12:17 UTC
Hi, I'm using this gateway. It's https://www.lidl-shop.cz/SILVERCREST-Centralni-jednotka-Zigbee-3-0-Smart-Home/p100306596. Everything seems fine, the device is found on the network with its IP, but then after entering the key I get this message.

 >Fill in the basic device details. The name entered here will be used to identify the integration itself (as seen in the Integrations page). You will add entities and give them names in the following steps.
Connection to device succeeded but no datapoints found, please try again. Create a new issue and include debug logs if problem persists.

This will appear in the log:
`2020-12-28 13:01:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`
`2020-12-28 13:01:43 DEBUG (MainThread) [custom_components.localtuya.discovery] Listening to broadcasts on UDP port 6666 and 6667`
`2020-12-28 13:01:46 DEBUG (MainThread) [custom_components.localtuya.discovery] Discovered device: {'ip': '200.200.1.245', 'gwId': 'bf5b8b7124fcb5422fri0d', 'active': 2, 'ablilty': 0, 'encrypt': True, 'productKey': 'keyyj3fy8x98arty', 'version': '3.4', 'token': True}
`
`2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Started heartbeat loop
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Sending command heartbeat (device type: type_0a)
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Send payload: b'{}'
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Waiting for sequence number -100
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Sending command status (device type: type_0a)
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Send payload: b'{"gwId":"bf5b8b7124fcb5422fri0d","devId":"bf5b8b7124fcb5422fri0d"}'
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Waiting for sequence number 1
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Connection lost: None
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Closing connection
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Wait was aborted for seqno 1
2020-12-28 13:02:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [bf5...i0d] Closing connection`

**Comment by postlund** [comment] 2020-12-28 12:21
Nobody has tried to implement support for gateways of any kinds yet, so they are deemed unsupported. If anyone wants to give it a try, it's free to do so! 👍

**Comment by postlund** [comment] 2020-12-28 12:22
This is also a duplicate of #69, so please use that issue instead.

**Closed by postlund** 2020-12-28 12:22 UTC
