### ISSUE TITLE
Circadian Lighting 

### ISSUE THREAD

**Issue by botts7** [rospogrigio/localtuya#127] opened 2020-10-30 07:54 UTC
**FIXED - I needed to set the options**
**min_colortemp: 3000**
**max_colortemp: 5700**

I have some RGBWW lights that Im trying to use with  Circadian Lighting component that will not be working for CT option? .Any insight into why it wont work?

works for XY and RGB but not CT?

Example of Attributes available

min_mireds: 154
max_mireds: 370
brightness: 254
color_temp: 299
hs_color: 27, 48.6
rgb_color: 255, 186, 131
xy_color: 0.468, 0.375
friendly_name: Fridge Light
supported_features: 19

**Comment by ultratoto14** [comment] 2020-10-30 09:50
@botts7 can you give an example of the DPs of the lights ?
[HOWTO-get-a-DPs-dump](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump)

**Comment by botts7** [comment] 2020-10-31 00:16
> @botts7 can you give an example of the DPs of the lights ?
> [HOWTO-get-a-DPs-dump](https://github.com/rospogrigio/localtuya/wiki/HOWTO-get-a-DPs-dump)
Thanks for taking a look 

AVAILABLE DPS ARE [{'20': True, '21': 'white', '22': 996, '23': 837, '24': '001b009d03e4', '25': '000e0d0000000000000000c80000', '26': 
0}]

**Comment by ultratoto14** [comment] 2020-10-31 13:51
Hi @botts7,

About your remarks: 

- _But trying to change values using the state attributes (YAML) has no effect_ < If you are talking about using the states tab in the dev tools, it's the expected behavior in HA, this is just there to update the value without triggerring anything.
- About the difference between this one and the lifx light, correct me if i'm wrong but the lifx one is not a color bulb. I think i understand the problem, due to the way the lights are handled, it's difficult to know if the command received is white only or colored. All the data is returned. I may check we just need to ignore color set if saturation is 0 (everything is managed in hs in the current implementation.)

**Comment by ultratoto14** [comment] 2020-10-31 14:31
Hi @botts7, can you try the fix on this branch [light_scene_fix](https://github.com/ultratoto14/localtuya/tree/light_scene_fix)

If you are using master branch, you can just replace the light.py file by this one [light.py](https://raw.githubusercontent.com/ultratoto14/localtuya/light_scene_fix/custom_components/localtuya/light.py)

**Comment by botts7** [comment] 2020-10-31 23:49
> Hi @botts7, can you try the fix on this branch [light_scene_fix](https://github.com/ultratoto14/localtuya/tree/light_scene_fix)
> 
> If you are using master branch, you can just replace the light.py file by this one [light.py](https://raw.githubusercontent.com/ultratoto14/localtuya/light_scene_fix/custom_components/localtuya/light.py)

here is the debug log


2020-11-01 10:41:26 DEBUG (SyncWorker_15) [custom_components.circadian_lighting.switch] light.bench_light_2 change from <state light.bench_light_2=on; min_mireds=175, max_mireds=333, brightness=254, color_temp=186, hs_color=(0, 0), rgb_color=(255, 255, 255), xy_color=(0.323, 0.329), friendly_name=Bench Light 2, supported_features=19 @ 2020-11-01T10:40:55.959801+11:00> to <state light.bench_light_2=on; min_mireds=175, max_mireds=333, brightness=254, color_temp=185, hs_color=(0, 0), rgb_color=(255, 255, 255), xy_color=(0.323, 0.329), friendly_name=Bench Light 2, supported_features=19 @ 2020-11-01T10:40:55.959801+11:00>

**Comment by botts7** [comment] 2020-11-01 00:02
> Hi @botts7,
> 
> About your remarks:
> 
> * _But trying to change values using the state attributes (YAML) has no effect_ < If you are talking about using the states tab in the dev tools, it's the expected behavior in HA, this is just there to update the value without triggerring anything.
> * About the difference between this one and the lifx light, correct me if i'm wrong but the lifx one is not a color bulb. I think i understand the problem, due to the way the lights are handled, it's difficult to know if the command received is white only or colored. All the configuration data are returned, color_temp, hs, rgb ... I may check we just need to ignore color set if saturation is 0 (everything is managed in hs in the current implementation.)

Lifx Light is also RGBCCT - the CCT is 2700k - 6500k
The Local Tuya lights CCT range is 3000k - 5700k

so setting the min max range in circadian lighting so either light doesnt cover the range has allowed the color temp to be changed properly by the component.

This was prior to the change of the light.py file, so I have not noticed any change, is there something you would like me to confirm/try?



Im using the CT option in circadian so excuse my ignorance but should the updated file have an effect on the hs_color?

**Comment by ultratoto14** [comment] 2020-11-01 09:39
Ok, so if i understand correctly, the problem is fixed ?
If it is the case, can you edit your firts message, add the link to the solution and close the issue ?

**Comment by botts7** [comment] 2020-11-01 09:43
> Ok, so if i understand correctly, the problem is fixed ?
> If it is the case, can you edit your first message, add the link to the solution and close the issue ?

Yes it seems so - Thanks for your help!!!

**Closed** 2020-11-01 09:42 UTC
Labels: enhancement
