### ISSUE TITLE
 socket.send() raised exception

### ISSUE THREAD

**Issue by garry0garry** [rospogrigio/localtuya#1410] opened 2023-05-25 19:29 UTC
Home Assistant 2023.5.4, Uptime 11 hours.
Local Tuya v5.2.0
Device: "HIPER Weather Station P1" aka "Tuya generic (324164718cce4edbc7d7) by Tuya" 

```
This error originated from a custom integration.

Logger: asyncio
Source: custom_components/localtuya/pytuya/__init__.py:768
Integration: LocalTuya (documentation, issues)
First occurred: 8:47:24 PM (379 occurrences)
Last logged: 10:21:56 PM

socket.send() raised exception.
```
What could it be?

**Comment by lionslair** [comment] 2023-05-26 03:00
I have the same error appearing.

```
This error originated from a custom integration.

Logger: asyncio
Source: custom_components/localtuya/pytuya/__init__.py:768
Integration: LocalTuya (documentation, issues)
First occurred: 12:23:51 AM (7181 occurrences)
Last logged: 10:58:58 AM

socket.send() raised exception.
```

**Comment by pbranly** [comment] 2023-05-26 03:34
Same here

**Comment by patrik-malina** [comment] 2023-05-26 09:02
Same here. It increase number of shown every second...
Having no problem in connections with devices.

**Comment by garry0garry** [comment] 2023-05-26 12:39
https://github.com/rospogrigio/localtuya/issues/1406#issuecomment-1564330661

**Comment by PachangaDad** [comment] 2023-05-26 14:32
Sae error here 43,978 times

**Comment by garry0garry** [comment] 2023-05-26 14:38
1. Disconnected
2. Trying to connect
3. Successfully connected
4. [asyncio] socket.send() raised exception.
...
N. [asyncio] socket.send() raised exception.

**Comment by paulius2k** [comment] 2023-05-26 14:44
I can confirm same behaviour.

**Comment by ghluhi** [comment] 2023-05-26 17:18
Same issue with light bulbs and multi-socket power strip.

**Comment by djdevil** [comment] 2023-05-28 08:37
Same here

**Comment by domoticasimoes** [comment] 2023-05-28 08:43
I have the same error

**Comment by garry0garry** [comment] 2023-05-28 08:45
The reason can be found like this:
```
logger:
   default: warning
   logs:
     custom_components.localtuya:debug
```
Example:
```
[custom_components.localtuya.common] [324...7d7] Disconnected - waiting for discovery broadcast
[custom_components.localtuya.common] [324...7d7] Trying to connect to 192.168.50.180...
[custom_components.localtuya.common] [324...7d7] Successfully connected to 192.168.50.180
[asyncio] socket.send() raised exception.
[asyncio] socket.send() raised exception.
```

**Comment by domoticasimoes** [comment] 2023-05-28 09:04
I can't resolve the error

**Comment by garry0garry** [comment] 2023-05-28 09:07
> I can't resolve the error

I got the error after 5 hours.

**Comment by domoticasimoes** [comment] 2023-05-28 09:08
but it still does not solve this error??

**Comment by garry0garry** [comment] 2023-05-28 17:42
@rospogrigio? Can you comment?

**Comment by rospogrigio** [comment] 2023-05-29 07:45
Don't know what to say, it's not happening in my setup and no relevant part was changed between 5.1.0 and 5.2.0. 
Closing this issue because it's a duplicate of #1406 , please check in the future before posting.

**Closed by rospogrigio** 2023-05-29 07:45 UTC
Labels: bug
