### ISSUE TITLE
Zigbee devices not seen

### ISSUE THREAD

**Issue by Stea73** [rospogrigio/localtuya#1160] opened 2022-12-01 15:28 UTC
Hello, 
How can I add in HA a Tuya Zigbee device (door sensor) that has been added to a Zigbee hub copatible with Tuya?
I can see the hub, but can't access the subdevice. 
I tried to add manually as binary sensor the device using  as the Host the hub IP (but using the door sensor's local/device Ids). 
The result is that I get an Binary sensor entity but it's not the door sensor, or its state is not updated

ANy suggestion?

**Comment by ajunio3** [comment] 2022-12-03 22:47
localtuya is not designed for Zigbee devices, but for Wi-Fi ones. Use Zigbee2Mqtt together with a controller and be happy

**Comment by atlantden** [comment] 2022-12-13 10:07
Zibee Gateways and several devices are already supported in the fork and works fine
https://github.com/leeyuentuen/localtuya/
It was grate if it will be merged to main code

**Comment by darth-aragoth** [comment] 2023-01-16 20:26
Fully agree, zigbee2mqtt is not a solution when you need Zigbee devices also in Tuya / Smartlife app.

**Comment by txelu** [comment] 2023-01-16 23:44
I think this is a duplicate of the #1120, which is asking to integrate the work previously done in  #739. I'd also like to have zigbee devices managed by LocalTuya.

**Comment by rospogrigio** [comment] 2023-09-14 12:53
I have introduced Zigbee support in PR #1493,  if anybody wants to test it and provide feedback, please comment in the PR.

**Closed by rospogrigio** 2023-09-14 12:53 UTC
