### ISSUE TITLE
Failure current_consumption update

### ISSUE THREAD

**Issue by davanda** [rospogrigio/localtuya#130] opened 2020-11-01 18:27 UTC
Hi, 
I installed localtuya and, after retrieving the localKeys, everything works, but I have a problem. 
The current_consumption value of the switch not update automatically, but if I open the app from the smartphone and go to the electric page, it also updates on hassio. 

I tried with both integration procedures: yaml and flow. 
I used  this PD:
current: 18 
current_consumption: 19 
voltage: 20 

Can you help me?
Thanks

**Comment by postlund** [comment] 2020-11-01 18:29
Duplicate of #87.

TL;DR: We know about this issue and we currently have no solution for it. See #87 for details.

**Closed by postlund** 2020-11-01 18:29 UTC
