### ISSUE TITLE
future versions of HA will cause issues

### ISSUE THREAD

**Issue by jjvandenberg** [rospogrigio/localtuya#981] opened 2022-08-03 18:54 UTC
custom_components.localtuya.number::LocaltuyaNumber is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
20:36:56 – (WAARSCHUWING) Nummer

**Comment by CloCkWeRX** [comment] 2022-08-07 09:21
Duplicate of #929

**Comment by Daneish** [comment] 2022-08-07 13:39
Should this one be closed off, to track it in just one issue?

**Comment by jjvandenberg** [comment] 2022-08-07 16:49
Duplicate of https://github.com/rospogrigio/localtuya/issues/929, closed

**Closed** 2022-08-07 16:51 UTC
Labels: bug
