### ISSUE TITLE
current_consumption updates interval ?

### ISSUE THREAD

**Issue by kingwap99** [rospogrigio/localtuya#393] opened 2021-03-12 03:53 UTC
I am installing this tuya smart socket with current_consumption 
https://img.ruten.com.tw/s2/6/ac/42/22108980442178_427.jpg
My problem is that the current_consumption only live (on HA) when I opened the Smart Life app and stay on the Electric screen to monitor the current_consumption.
please help me to solve this issue, thanks .

**Comment by postlund** [comment] 2021-03-12 08:43
Duplicate of #87.

**Closed by postlund** 2021-03-12 08:43 UTC
